<?php
/**
 * TODO Add @file block for HtmlBacktraceRendererTest.php
 *
 * @author Travis Uribe <travis@tvanc.com>
 */

namespace tvanc\backtrace\Test\Render;

use tvanc\backtrace\Render\ExceptionRendererInterface;
use tvanc\backtrace\Render\HtmlExceptionRenderer;

/**
 * TODO Document class HtmlBacktraceRendererTest
 */
class HtmlExceptionRendererTest extends AbstractExceptionRendererTest
{
    public function testRender()
    {
        parent::testRender(); // TODO: Change the autogenerated stub
    }


    public function testRenderStage()
    {
        parent::testRenderStage(); // TODO: Change the autogenerated stub
    }


    public function getRenderer(): ExceptionRendererInterface
    {
        return new HtmlExceptionRenderer(
            realpath(__DIR__ . '/../../view'),
            realpath(__DIR__ . '/../../public/assets'),
            'throwable.php',
            'stage.php'
        );
    }
}
